from datetime import datetime, date, timedelta

import requests
import json
import pickle
from jinja2 import Template
import plotly.graph_objects as go
ownurl = "http://94.79.54.21:3000"
token = "dIlUIIpKrjCcrmmM"
email = "dvchernov_1@miem.hse.ru"
myname = "Чернов Даниил Викторович"
dataGit = {
                    "studEmail": email,
                                    "beginDate": "2022-01-01" ,
                                                        "endDate": "2022-04-01",
                                                                                "timeRange": 1,
                                                                                                            "hideMerge": True,
                                                                                                                                            "token": token
                                                                                                                                                                            }
dataZulip = {
                    "studEmail": email,
                                    "beginDate": "2021-10-10",
                                                        "endDate": "2022-04-20",
                                                                                "timeRange": 1,
                                                                                                            "token": token

                                                                                                                                        }
dataJitsi = {
                    "studEmail": email,
                                    "beginDate": "2021-03-10",
                                                        "endDate": "2022-04-01",

                                                                                    "beginTime": "10:00:00.000",
                                                                                                                    "endTime": "21:00:00.000",
                                                                                                                                                        "token": token

                                                                                                                                                                                            }
def Git():

        EndComits ={}
            response = requests.post(ownurl + r"/api/git/getDataPerWeek", json=dataGit).json()
                AllCommits =0
                    for index in response["projects"]:
                                Commits = {}
                                        for index1 in index["commits_stats"]:
                                                        Commits[index1["beginDate"][:15]] = index1["commitCount"]
                                                                    AllCommits += index1["commitCount"]

                                                                            EndComits[index["name"]] = Commits
                                                                                date =['Sat Jan 01 2022', 'Mon Jan 03 2022', 'Mon Jan 10 2022', 'Mon Jan 17 2022', 'Mon Jan 24 2022', 'Mon Jan 31 2022', 'Mon Feb 07 2022', 'Mon Feb 14 2022', 'Mon Feb 21 2022', 'Mon Feb 28 2022', 'Mon Mar 07 2022', 'Mon Mar 14 2022', 'Mon Mar 21 2022', 'Mon Mar 28 2022']
                                                                                    d =[]
                                                                                        d2 = []
                                                                                            for index in EndComits.keys():
                                                                                                        d += EndComits[index].values()

                                                                                                            for i in range(14):
                                                                                                                        d2.append(d[i]+d[i+14]+d[i+28]+d[i+42])
                                                                                                                            EEndComits = {}
                                                                                                                                i = 0
                                                                                                                                    for i in range(14):
                                                                                                                                                EEndComits[date[i]] = d2[i]
                                                                                                                                                    return EEndComits, AllCommits

                                                                                                                                                def Taiga():
                                                                                                                                                        taiga= {}
                                                                                                                                                            for i in range(1, 4):
                                                                                                                                                                        if i == 2:
                                                                                                                                                                                        for j in range(1, 29):
                                                                                                                                                                                                            if j < 10:
                                                                                                                                                                                                                                    taiga[f'2022-0{i}-0{j}'] = 0
                                                                                                                                                                                                                                                    else:
                                                                                                                                                                                                                                                                            taiga[f'2022-0{i}-{j}'] = 0
                                                                                                                                                                                                                                                                                    else:
                                                                                                                                                                                                                                                                                                    for j in range(1, 32):
                                                                                                                                                                                                                                                                                                                        if j < 10:
                                                                                                                                                                                                                                                                                                                                                taiga[f'2022-0{i}-0{j}'] = 0
                                                                                                                                                                                                                                                                                                                                                                else:
                                                                                                                                                                                                                                                                                                                                                                                        taiga[f'2022-0{i}-{j}'] = 0
                                                                                                                                                                                                                                                                                                                                                                                            story = list()
                                                                                                                                                                                                                                                                                                                                                                                                tasks = list()
                                                                                                                                                                                                                                                                                                                                                                                                    name = 'Даниил Чернов'
                                                                                                                                                                                                                                                                                                                                                                                                        headers = {"x-disable-pagination": "true"}
                                                                                                                                                                                                                                                                                                                                                                                                            Taiga1= requests.get("https://track.miem.hse.ru/api/v1/userstories", headers=headers).json()
                                                                                                                                                                                                                                                                                                                                                                                                                Taiga2 = requests.get("https://track.miem.hse.ru/api/v1/tasks", headers=headers).json()
                                                                                                                                                                                                                                                                                                                                                                                                                    for index in Taiga1:
                                                                                                                                                                                                                                                                                                                                                                                                                                try:
                                                                                                                                                                                                                                                                                                                                                                                                                                                if index['assigned_to_extra_info']['full_name_display'] == name:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    story.append(index)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            except:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            pass
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            for index in Taiga2:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        try:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if index['assigned_to_extra_info']['full_name_display'] == name:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            tasks.append(index)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    except:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    pass
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    for item in taiga.keys():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                for task in tasks:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if str(task['created_date'][:-14]) == item:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    taiga[item] += 1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return len(story), len(tasks), taiga




                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    def Zulip():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            response = requests.post(ownurl + r'/api/zulip/getData', json=dataZulip).json()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Zulip = {}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    channels = []
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        count = 0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            for index in response["stats"]:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if index["messageCount"] != 0:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Zulip[index["beginDate"][:15]] = index["messageCount"]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            for index in response["messages"]:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if index["name"] not in channels:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        channels.append(index["name"])

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return Zulip


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        def Jitsi():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                response = requests.post(ownurl + r'/api/jitsi/sessions', json=dataJitsi).json()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    jitsi = {}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        rooms ={}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            for index in response:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        rooms[index["room"]] = index["room"]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if index["room"] == "ps":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                jitsi[index["date"].replace("-", " ")] = jitsi.setdefault(index["date"].replace("-", " "), 0) + 1

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return jitsi, rooms

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Commits, AllCommits = Git()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                story, task, DataTaiga = Taiga()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                FirstFile = open('/home/prsem/dvchernov_1/dvchernov_1/lab_5.html', encoding='utf8').read()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                tp = Template(FirstFile)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                zulip = Zulip()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                jitsiG, rooms = Jitsi()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                with open('/var/www/html/students/dvchernov_1/dvchernov_1.html', 'w', encoding='utf8') as f:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        f.write(tp.render(data=datetime.now().isoformat(),JitsiRooms = rooms.values(), gitLin = AllCommits, GitGraf = go.Figure([go.Bar(x = list(Commits.keys()), y = list(Commits.values()))],layout=go.Layout(template='plotly_dark')).to_html(), DataTaiga = go.Figure(go.Scatter(x = list(DataTaiga.keys()), y = list(DataTaiga.values())), layout=go.Layout(template='plotly_dark')).to_html(), DataZulip = go.Figure([go.Bar(x = list(zulip.keys()), y = list(zulip.values()))],layout=go.Layout(template='plotly_dark')).to_html(), DataJitsi = go.Figure(go.Scatter(x = list(jitsiG.keys()), y = list(jitsiG.values())), layout=go.Layout(template='plotly_dark')).to_html()))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        f.close()

